#camel:
#  springboot:
#    main-run-controller: true

server:
  port: ${SERVER_PORT:8080}

camel:
  servlet:
    mapping:
      context-path: /*
  component:
    servlet:
      scheme: ${DESTINATION_SERVER_SCHEME:http}
      host: ${DESTINATION_SERVER_HOST:localhost}
      port: ${DESTINATION_SERVER_PORT:8080}
      sourceEndpointPath: ${SOURCE_ENDPOINT_PATH:story/task}
      destinationEndpointPath: ${DESTINATION_ENDPOINT_PATH:swagger-ui/index.html}