#camel:
#  springboot:
#    main-run-controller: true

server:
  port: ${SERVER_PORT:8080}

camel:
  servlet:
    mapping:
      context-path: /*
  component:
    netty-http:
      scheme: ${CAMEL_SERVER_SCHEME:http}
      host: ${CAMEL_SERVER_HOST:localhost}
      port: ${CAMEL_SERVER_PORT:9090}